### ISSUE TITLE
[#QUESTION] How to replace text to image

### ISSUE THREAD

**Issue by yuliantosb** [silverslice/excel-template#3]
Hello sir, I really need this feature, is it possible to replace a text to images?
thanks :)

**Comment by silverslice** [comment]
Hi! Unfortunately no. Placing images into excel files is not a trivail problem. Try to use https://github.com/PHPOffice/PHPExcel

**Comment by yuliantosb** [comment]
@silverslice Ugh that's make me sad, but thanks for your comment, but perhaps will you add this feature in further? :smiley:
